identifier: kdxaa8s002zf842d
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: scully-blog
homeFolder: /Users/mojcacolnik/Desktop/Angular Projects/scully-blog
distFolder: dist/scully-blog
outDir: /Users/mojcacolnik/Desktop/Angular Projects/scully-blog/dist/static
handle404: ''
allowErrorCollect: false
